config/routes.rb
Elovation::Application.routes.draw do
  resources :games do
    resources :results, only: [:create, :destroy, :new]
    resources :ratings, only: [:index]
  end

  resources :players do
    resources :games, only: [:show], controller: 'player_games'
  end

  get '/dashboard' => 'dashboard#show', as: :dashboard
  root to: 'dashboard#show'
end

app/models/player.rb
class Player < ActiveRecord::Base
  has_many :ratings, dependent: :destroy do
    def find_or_create(game)
      where(game_id: game.id).first || create({game: game, pro: false}.merge(game.rater.default_attributes))
    end
  end

  has_and_belongs_to_many :teams

  has_many :results, through: :teams do
    def against(opponent)
      joins("INNER JOIN teams AS other_teams ON results.id = other_teams.result_id")
        .where("other_teams.id != teams.id")
        .joins("INNER JOIN players_teams AS other_players_teams ON other_teams.id = other_players_teams.team_id")
        .where("other_players_teams.player_id = ?", opponent)
    end

    def losses
      where("teams.rank > ?", Team::FIRST_PLACE_RANK)
    end

  end

  before_destroy do
    results.each { |result| result.destroy }
  end

  validates :name, uniqueness: true, presence: true
  validates :email, allow_blank: true, format: /@/

  def as_json
    {
      name: name,
      email: email
    }
  end

  def recent_results
    results.order("created_at DESC").limit(5)
  end

  def rewind_rating!(game)
    rating = ratings.where(game_id: game.id).first
    rating.rewind!
  end

  def total_ties(game)
    results.where(game_id: game).to_a.count { |r| r.tie? }
  end

  def ties(game, opponent)
    results.where(game_id: game).against(opponent).to_a.count { |r| r.tie? }
  end

  def total_wins(game)
    results.where(game_id: game, teams: { rank: Team::FIRST_PLACE_RANK }).to_a.count { |r| !r.tie? }
  end

  def wins(game, opponent)
    results.where(game_id: game, teams: {rank: Team::FIRST_PLACE_RANK}).against(opponent).to_a.count { |r| !r.tie? }
  end


end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  before_action :set_player, only: [:edit, :destroy, :show, :update]

  def create
    @player = Player.new(player_params)

    if @player.save
      redirect_to dashboard_path
    else
      render :new
    end
  end

  def destroy
    @player.destroy if @player.results.empty?
    redirect_to dashboard_path
  end

  def edit
  end

  def new
    @player = Player.new
  end

  def show
  end

  def update
    if @player.update_attributes(player_params)
      redirect_to player_path(@player)
    else
      render :edit
    end
  end

  private

  def set_player
    @player = Player.find(params[:id])
  end

  def player_params
    params.require(:player).permit(:name, :email)
  end
end

app/views/players/_form.html.erb
<%= form_for @player, html: {class: "form-horizontal"} do |f| %>
  <%= f.error_messages %>

  <h1>Player</h1>
  
  <div class="control-group">
    <%= f.label :name, class: "control-label" %>
    <div class="controls">
      <%= f.text_field :name, class: "input-xlarge" %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :email, class: "control-label" %>
    <div class="controls">
      <%= f.text_field :email, class: "input-xlarge" %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit class: "btn btn-primary" %>
    <%= link_to "Cancel", root_path, class: "btn btn-warning" %>
  </div>

  <small class="description attribution">
    Avatar provided by <a href="http://gravatar.com/">Gravatar</a>, a global avatar service.
  </small>

<% end %>

app/views/players/_rating.html.erb
<li><%= link_to rating.game.name, player_game_path(@player, rating.game) %> - <%= rating.value %></li>

app/views/players/edit.html.erb
<%= render 'form' %>

app/views/players/new.html.erb
<%= render 'form' %>

app/views/players/show.html.erb
<h1>
  <%= image_tag(gravatar_url(@player, size: 80)) %>
  <%= @player.name %>
</h1>
  
<section class="action-buttons">
  <span><%= link_to 'Edit Player', edit_player_path(@player), class: "btn btn-primary" %></span>
  <% if @player.results.empty? %>
    <span><%= link_to "Delete", player_path(@player), method: :delete, confirm: "Are you sure?", class: "btn btn-danger" %></span>
  <% end %>
</section>

<div class="row-fluid">
  <div class="span8">
    <h2>Recent Results</h2>
    <% if @player.recent_results.any? %>
      <%= render partial: 'shared/results', object: @player.recent_results, locals: {show_game: true} %>
    <% else %>
      <span>No results, play some games!</span>
    <% end %>
  </div>
  <div class="span4">
    <h2>Ratings</h2>
    <ol>
      <%= render partial: 'rating', collection: @player.ratings %>
    </ol>
  </div>
</div>